<a href="https://colab.research.google.com/github/ramanji567/clenaing-and-baseline-of-MAE-in-car-data-set/blob/main/Evaluate_MAE_and_baseline_any_machine_learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task 1 : Explore and Identify issues

In [53]:
import pandas as pd
df = pd.read_csv('/content/used_cars_messy (2).csv')
df

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,2581,Renault Duster,Renault,Duster,7,67647,Dealer,Diesel,Manual,19.87,1461.0,83.80,5.0,575000.0
1,224,Maruti Wagon R,Maruti,Wagon R,3,52000,Dealer,CNG,Manual,33.54,998.0,67.04,5.0,435000.0
2,1803,Honda City,Honda,City,3,48959,Dealer,Petrol,Manual,NaN,1497.0,117.60,5.0,875000.0
3,2728,Mahindra Scorpio,Mahindra,Scorpio,6,82000,dealer,Diesel,Manual,15.4,2179.0,NaN,8.0,925000.0
4,14160,Mahindra XUV500,Mahindra,XUV500,4,34000,Dealer,Diesel,Automatic,16.0,2179.0,140.00,7.0,1175000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15656,6581,Maruti Ertiga,Maruti,Ertiga,7,127731,Dealer,Diesel,Manual,20.77,1248.0,88.80,7.0,665000.0
15657,17029,Volkswagen Vento,Volkswagen,Vento,11,59000,Dealer,Petrol,Manual,16.09,NaN,103.20,5.0,249000.0
15658,6839,Maruti Wagon R,Maruti,Wagon R,7,20000,Individual,Petrol,Manual,20.51,998.0,67.04,5.0,250000.0
15659,1104,Hyundai i20,Hyundai,i20,2,15000,Dealer,Petrol,Manual,18.6,1197.0,81.86,5.0,620000.0
15660,9295,Maruti Ciaz,Maruti,Ciaz,2,30000,Individual,Petrol,Automatic,20.28,1462.0,103.25,5.0,960000.0

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15661 entries, 0 to 15660
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15661 non-null  int64
 1   car_name           15661 non-null  object
 2   brand              15661 non-null  object
 3   model              15661 non-null  object
 4   vehicle_age        15661 non-null  int64
 5   km_driven          15661 non-null  object
 6   seller_type        15661 non-null  object
 7   fuel_type          15661 non-null  object
 8   transmission_type  15661 non-null  object
 9   mileage            14376 non-null  object
 10  engine             13792 non-null  float64
 11  max_power          14862 non-null  float64
 12  seats              15218 non-null  float64
 13  selling_price      15503 non-null  float64
dtypes: float64(4), int64(2), object(8)
memory usage: 1.7+ MB

I have observed data qualities that is mileage data type is wrong  we have cahnge that into float and km_driven wrong data type so we have to change that also into integer data type and drop of column unnamed

mileage , engine,max_power,seats,selling_price these columns having null values

In [55]:
df.isnull().sum()

Unnamed: 0              0
car_name                0
brand                   0
model                   0
vehicle_age             0
km_driven               0
seller_type             0
fuel_type               0
transmission_type       0
mileage              1285
engine               1869
max_power             799
seats                 443
selling_price         158
dtype: int64

In [56]:
df.describe()

,Unnamed: 0,vehicle_age,engine,max_power,seats,selling_price
count,15661.000000,15661.000000,13792.000000,14862.000000,15218.000000,1.550300e+04
mean,9808.189643,6.036843,1480.489342,100.513582,5.324418,1.032764e+06
std,5642.981540,3.015072,511.446057,42.854632,0.805993,1.607380e+07
min,0.000000,0.000000,793.000000,38.400000,0.000000,5.000000e+02
25%,4901.000000,4.000000,1197.000000,74.000000,5.000000,3.850000e+05
50%,9858.000000,6.000000,1248.000000,88.500000,5.000000,5.550000e+05
75%,14666.000000,8.000000,1582.000000,117.300000,5.000000,8.250000e+05
max,19543.000000,29.000000,6592.000000,626.000000,9.000000,1.000000e+09

In [57]:
df.shape

(15661, 14)

In [58]:
df.isnull().sum()*100/len(df)

Unnamed: 0            0.000000
car_name              0.000000
brand                 0.000000
model                 0.000000
vehicle_age           0.000000
km_driven             0.000000
seller_type           0.000000
fuel_type             0.000000
transmission_type     0.000000
mileage               8.205095
engine               11.934104
max_power             5.101845
seats                 2.828683
selling_price         1.008876
dtype: float64

Task 2 : clean the data

In [59]:
df=df.dropna(subset =["selling_price"])
df

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,2581,Renault Duster,Renault,Duster,7,67647,Dealer,Diesel,Manual,19.87,1461.0,83.80,5.0,575000.0
1,224,Maruti Wagon R,Maruti,Wagon R,3,52000,Dealer,CNG,Manual,33.54,998.0,67.04,5.0,435000.0
2,1803,Honda City,Honda,City,3,48959,Dealer,Petrol,Manual,NaN,1497.0,117.60,5.0,875000.0
3,2728,Mahindra Scorpio,Mahindra,Scorpio,6,82000,dealer,Diesel,Manual,15.4,2179.0,NaN,8.0,925000.0
4,14160,Mahindra XUV500,Mahindra,XUV500,4,34000,Dealer,Diesel,Automatic,16.0,2179.0,140.00,7.0,1175000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15656,6581,Maruti Ertiga,Maruti,Ertiga,7,127731,Dealer,Diesel,Manual,20.77,1248.0,88.80,7.0,665000.0
15657,17029,Volkswagen Vento,Volkswagen,Vento,11,59000,Dealer,Petrol,Manual,16.09,NaN,103.20,5.0,249000.0
15658,6839,Maruti Wagon R,Maruti,Wagon R,7,20000,Individual,Petrol,Manual,20.51,998.0,67.04,5.0,250000.0
15659,1104,Hyundai i20,Hyundai,i20,2,15000,Dealer,Petrol,Manual,18.6,1197.0,81.86,5.0,620000.0
15660,9295,Maruti Ciaz,Maruti,Ciaz,2,30000,Individual,Petrol,Automatic,20.28,1462.0,103.25,5.0,960000.0

In [60]:
df.isnull().sum()

Unnamed: 0              0
car_name                0
brand                   0
model                   0
vehicle_age             0
km_driven               0
seller_type             0
fuel_type               0
transmission_type       0
mileage              1269
engine               1852
max_power             791
seats                 438
selling_price           0
dtype: int64

In [61]:
list_1 =df["km_driven"].sample(100).tolist()
print(list_1)

['45000', '49000', '17745', '19000', '5000', '50000', '20000', '37859', '30000', '25451', '69000', '76000', '40000', '2000', '62000', '70000', '55000', '65122', '25000', '30000', '50000', '90000', '120000', '90000', '23000', '115000', '44000', '45000', '42676', '38819', '79000', '20000', '29000', '89000', '48000', '52250', '50000', '20000', '46000', '80000', '22000', '74000', '28960', '4000', '27300', '38000', '53000', '140000', '50000', '41473', '162828', '90000', '95000', '22597', '41604', '60000', '47230', '57429', '28014', '95000', '13000', '101689', '120000', '95321', '28000', '43000', '19000', '36000', '39000', '112000', '4104', '58000', '75000', '43000', '50000', '44000', '30000', '71000', '39000', '133000', '25000', '106000', '60000', '57000', '1830', '57000', '90000', '65067', '25000', '50000', '76602', '63630', '120000', '120000', '41000', '70000', '74844', '32000', '84000', '75000 km']

In [62]:
list_2 =df["mileage"].sample(100).tolist()
print(list_2)

['22.54', '15.4', '22.48', '19.3', '21.38', '16.2', '15.6', '22.32', '18.5', '17.4', '17.0', '24.3', '25.8', '25.83', '17.0', nan, '20.45', '11.5', '24.3', '14.1', '20.51', '15.2', '13.0 kmpl', '24.52', '23.1', '11.57', '20.51', '30.47', '16.36', '21.13', '11.74', '22.7', '17.11', '19.81', '20.14', '16.55', '15.1', '20.45', '20.0', '18.9', '22.54', '12.99', '17.4', '15.74', '18.6', nan, '26.59', '23.26', '18.9', '12.05', '15.6', '21.4', '22.0', '15.4', '24.3', '14.84', '14.0', '15.96', '17.21', '18.9', '18.0', '14.84', '14.49', '11.33', '17.2', '19.16', '13.1', '23.4', '18.9', '22.77', '24.04', '26.0', nan, '21.19', '20.77', '13.6', '22.0', '21.56', '16.55', '12.99', nan, nan, '23.95', '17.21', '16.95', '16.0', '12.8', '13.68', '22.54', '20.0', '20.4', '17.5', '20.36', '18.0', '23.26', '14.8', '16.8', '19.0', '19.27', nan]

In [63]:
df[df["km_driven"].astype(str).str.contains('kms')]

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
80,4871,Mahindra XUV500,Mahindra,XUV500,6,42000 kms,Dealer,Diesel,Manual,15.1,2179.0,140.00,7.0,950000.0
244,15186,Renault Duster,Renault,Duster,5,62000 kms,Individual,Diesel,Manual,19.87,1461.0,83.80,5.0,700000.0
324,2767,Hyundai i20,Hyundai,i20,9,40000 kms,Dealer,Diesel,Manual,21.9,1396.0,NaN,5.0,435000.0
370,18113,Ford Aspire,Ford,Aspire,5,43652 kms,Dealer,Petrol,Manual,18.16,1196.0,86.80,5.0,430000.0
721,3117,Honda City,Honda,City,10,100000 kms,Individual,Petrol,Manual,17.0,1497.0,118.00,5.0,380000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14403,17660,Honda Civic,Honda,Civic,2,16502 kms,Dealer,Petrol,Automatic,16.5,1799.0,139.46,NaN,2100000.0
14977,6415,Maruti Swift,Maruti,Swift,7,70000 kms,Individual,Petrol,Manual,18.6,1197.0,85.80,5.0,370000.0
15170,2436,Honda Amaze,Honda,Amaze,8,31497 kms,Dealer,Petrol,Manual,18.0,1198.0,86.70,5.0,393000.0
15449,7555,Hyundai i20,Hyundai,i20,3,15000 kms,Dealer,Petrol,Manual,18.6,1197.0,81.83,5.0,660000.0
15602,18385,Mahindra XUV500,Mahindra,XUV500,6,80000 kms,Individual,Diesel,Manual,NaN,2179.0,140.00,7.0,925000.0

In [64]:
df[df["mileage"].astype(str).str.contains('kmpl')]

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
91,14883,Maruti Wagon R,Maruti,Wagon R,4,30000,Individual,CNG,Manual,33.54 kmpl,998.0,67.04,5.0,450000.0
175,9041,Toyota Innova,Toyota,Innova,5,66240,Dealer,Diesel,Manual,13.68 kmpl,2393.0,147.80,7.0,1675000.0
384,8694,Maruti Alto,Maruti,Alto,3,38000,Dealer,Petrol,Manual,22.74 kmpl,796.0,47.30,5.0,325000.0
393,8711,Honda City,Honda,City,5,78236,Dealer,Petrol,Manual,17.4 kmpl,1497.0,NaN,5.0,651000.0
518,17379,Maruti Ciaz,Maruti,Ciaz,1,6003,Trustmark Dealer,Petrol,Manual,21.56 kmpl,1462.0,103.25,5.0,875000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15528,17056,Maruti Alto,Maruti,Alto,8,25000,Individual,Petrol,Manual,22.74 kmpl,796.0,47.30,5.0,210000.0
15554,15211,Renault KWID,Renault,KWID,2,8500,Dealer,Petrol,Automatic,24.04 kmpl,999.0,67.00,5.0,425000.0
15579,12962,Hyundai Creta,Hyundai,Creta,5,55000,Dealer,Diesel,Automatic,17.01 kmpl,NaN,126.20,5.0,990000.0
15618,248,Datsun GO,Datsun,GO,5,33350,Individual,Petrol,Manual,19.44 kmpl,1198.0,67.00,7.0,320000.0
15635,6414,Maruti Ciaz,Maruti,Ciaz,4,57000,Dealer,Diesel,Manual,28.09 kmpl,1248.0,88.50,5.0,720000.0

In [65]:
df["km_driven"]=(df['km_driven'].astype(str).str.replace("kms",'').str.replace('km','').str.replace(',',''))
df['km_driven'] =pd.to_numeric(df['km_driven'])
df.head(10)

/tmp/ipykernel_11543/1824428950.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["km_driven"]=(df['km_driven'].astype(str).str.replace("kms",'').str.replace('km','').str.replace(',',''))
/tmp/ipykernel_11543/1824428950.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['km_driven'] =pd.to_numeric(df['km_driven'])

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,2581,Renault Duster,Renault,Duster,7,67647,Dealer,Diesel,Manual,19.87,1461.0,83.80,5.0,575000.0
1,224,Maruti Wagon R,Maruti,Wagon R,3,52000,Dealer,CNG,Manual,33.54,998.0,67.04,5.0,435000.0
2,1803,Honda City,Honda,City,3,48959,Dealer,Petrol,Manual,NaN,1497.0,117.60,5.0,875000.0
3,2728,Mahindra Scorpio,Mahindra,Scorpio,6,82000,dealer,Diesel,Manual,15.4,2179.0,NaN,8.0,925000.0
4,14160,Mahindra XUV500,Mahindra,XUV500,4,34000,Dealer,Diesel,Automatic,16.0,2179.0,140.00,7.0,1175000.0
5,4259,Hyundai i10,Hyundai,i10,12,73000,Dealer,Petrol,Manual,20.36,1197.0,78.90,5.0,190000.0
6,2128,Hyundai i20,Hyundai,i20,12,88000,Dealer,Petrol,Manual,18.5,NaN,80.00,5.0,275000.0
7,6137,Maruti Wagon R,Maruti,Wagon R,7,50000,Individual,Petrol,Manual,20.51,NaN,67.04,5.0,351000.0
8,16919,Ford Freestyle,Ford,Freestyle,2,30000,individual,Diesel,Manual,24.4,1498.0,98.63,5.0,775000.0
9,2837,Maruti Swift Dzire,Maruti,Swift Dzire,10,75220,Dealer,Diesel,Manual,19.3,1248.0,73.90,5.0,390000.0

In [66]:
df['mileage']=(df['mileage'].astype(str).str.replace('kmpl','').str.strip())
df['mileage'] = pd.to_numeric(df['mileage'],errors='coerce')
df.head(10)

/tmp/ipykernel_11543/3353929806.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['mileage']=(df['mileage'].astype(str).str.replace('kmpl','').str.strip())
/tmp/ipykernel_11543/3353929806.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['mileage'] = pd.to_numeric(df['mileage'],errors='coerce')

,Unnamed: 0,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,2581,Renault Duster,Renault,Duster,7,67647,Dealer,Diesel,Manual,19.87,1461.0,83.80,5.0,575000.0
1,224,Maruti Wagon R,Maruti,Wagon R,3,52000,Dealer,CNG,Manual,33.54,998.0,67.04,5.0,435000.0
2,1803,Honda City,Honda,City,3,48959,Dealer,Petrol,Manual,NaN,1497.0,117.60,5.0,875000.0
3,2728,Mahindra Scorpio,Mahindra,Scorpio,6,82000,dealer,Diesel,Manual,15.40,2179.0,NaN,8.0,925000.0
4,14160,Mahindra XUV500,Mahindra,XUV500,4,34000,Dealer,Diesel,Automatic,16.00,2179.0,140.00,7.0,1175000.0
5,4259,Hyundai i10,Hyundai,i10,12,73000,Dealer,Petrol,Manual,20.36,1197.0,78.90,5.0,190000.0
6,2128,Hyundai i20,Hyundai,i20,12,88000,Dealer,Petrol,Manual,18.50,NaN,80.00,5.0,275000.0
7,6137,Maruti Wagon R,Maruti,Wagon R,7,50000,Individual,Petrol,Manual,20.51,NaN,67.04,5.0,351000.0
8,16919,Ford Freestyle,Ford,Freestyle,2,30000,individual,Diesel,Manual,24.40,1498.0,98.63,5.0,775000.0
9,2837,Maruti Swift Dzire,Maruti,Swift Dzire,10,75220,Dealer,Diesel,Manual,19.30,1248.0,73.90,5.0,390000.0

In [67]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15503 entries, 0 to 15660
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         15503 non-null  int64
 1   car_name           15503 non-null  object
 2   brand              15503 non-null  object
 3   model              15503 non-null  object
 4   vehicle_age        15503 non-null  int64
 5   km_driven          15503 non-null  int64
 6   seller_type        15503 non-null  object
 7   fuel_type          15503 non-null  object
 8   transmission_type  15503 non-null  object
 9   mileage            14234 non-null  float64
 10  engine             13651 non-null  float64
 11  max_power          14712 non-null  float64
 12  seats              15065 non-null  float64
 13  selling_price      15503 non-null  float64
dtypes: float64(5), int64(3), object(6)
memory usage: 1.8+ MB

In [68]:
df.columns

Index(['Unnamed: 0', 'car_name', 'brand', 'model', 'vehicle_age', 'km_driven',
       'seller_type', 'fuel_type', 'transmission_type', 'mileage', 'engine',
       'max_power', 'seats', 'selling_price'],
      dtype='object')

In [69]:
df = df.drop(columns=['Unnamed: 0','car_name','model'])
df.head(5)

,brand,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Renault,7,67647,Dealer,Diesel,Manual,19.87,1461.0,83.80,5.0,575000.0
1,Maruti,3,52000,Dealer,CNG,Manual,33.54,998.0,67.04,5.0,435000.0
2,Honda,3,48959,Dealer,Petrol,Manual,NaN,1497.0,117.60,5.0,875000.0
3,Mahindra,6,82000,dealer,Diesel,Manual,15.40,2179.0,NaN,8.0,925000.0
4,Mahindra,4,34000,Dealer,Diesel,Automatic,16.00,2179.0,140.00,7.0,1175000.0

In [70]:
print(f"Unique before :{df['brand'].nunique()}")
df['brand']=df['brand'].str.strip()
print(f"Unique after : {df["brand"].nunique()}")

Unique before :80
Unique after : 32

In [71]:
print(df['brand'].value_counts())

brand
Maruti           5020
Hyundai          3002
Honda            1495
Mahindra         1015
Toyota            801
Ford              792
Volkswagen        627
Renault           539
BMW               440
Tata              433
Mercedes-Benz     336
Skoda             335
Audi              193
Datsun            170
Jaguar             61
Land Rover         51
Jeep               42
Kia                33
Porsche            22
Volvo              20
MG                 19
Mini               17
Nissan             11
Lexus              10
Isuzu               8
Bentley             3
ISUZU               2
Maserati            2
Ferrari             1
Mercedes-AMG        1
Force               1
Rolls-Royce         1
Name: count, dtype: int64

In [72]:
df['fuel_type'].unique()

array(['Diesel', 'CNG', 'Petrol', 'Petrol ', 'DIESEL', ' Petrol',
       'petrol ', 'PETROL', ' Diesel', 'diesel ', 'LPG', 'petrol',
       'diesel', 'Electric'], dtype=object)

In [73]:
df['fuel_type'] =df['fuel_type'].str.strip().str.title()
df['fuel_type'].unique()

array(['Diesel', 'Cng', 'Petrol', 'Lpg', 'Electric'], dtype=object)

In [74]:
df['seller_type'].unique()

array(['Dealer', 'dealer', 'Individual', 'individual', 'DEALER',
       'Trustmark Dealer', 'Individul', 'Individuall', 'Delaer'],
      dtype=object)

In [75]:
df['seller_type']=df['seller_type'].str.strip().str.title()
df["seller_type"].unique()

array(['Dealer', 'Individual', 'Trustmark Dealer', 'Individul',
       'Individuall', 'Delaer'], dtype=object)

In [76]:
map = {
    "Individuall":"Individual",
    "Individul":"Individual",
    "Delaer":"Dealer"
}
df["seller_type"]=df["seller_type"].replace(map)

In [77]:
df["seller_type"].unique()

array(['Dealer', 'Individual', 'Trustmark Dealer'], dtype=object)

In [78]:
df["seller_type"].value_counts()

seller_type
Dealer              9592
Individual          5738
Trustmark Dealer     173
Name: count, dtype: int64

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15503 entries, 0 to 15660
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              15503 non-null  object
 1   vehicle_age        15503 non-null  int64
 2   km_driven          15503 non-null  int64
 3   seller_type        15503 non-null  object
 4   fuel_type          15503 non-null  object
 5   transmission_type  15503 non-null  object
 6   mileage            14234 non-null  float64
 7   engine             13651 non-null  float64
 8   max_power          14712 non-null  float64
 9   seats              15065 non-null  float64
 10  selling_price      15503 non-null  float64
dtypes: float64(5), int64(2), object(4)
memory usage: 1.4+ MB

In [80]:
for col in ["engine",'mileage','max_power']:
  median_val =df[col].median()
  df[col]=df[col].fillna(median_val)
  print(f"filled{col}with median:{median_val} ")

filledenginewith median:1248.0
filledmileagewith median:19.67
filledmax_powerwith median:88.5

In [81]:
seats_mode =df['seats'].mode()[0]
df['seats'] = df["seats"].fillna(seats_mode)

In [82]:
df.isnull().sum()*100/len(df)

brand                0.0
vehicle_age          0.0
km_driven            0.0
seller_type          0.0
fuel_type            0.0
transmission_type    0.0
mileage              0.0
engine               0.0
max_power            0.0
seats                0.0
selling_price        0.0
dtype: float64

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15503 entries, 0 to 15660
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              15503 non-null  object
 1   vehicle_age        15503 non-null  int64
 2   km_driven          15503 non-null  int64
 3   seller_type        15503 non-null  object
 4   fuel_type          15503 non-null  object
 5   transmission_type  15503 non-null  object
 6   mileage            15503 non-null  float64
 7   engine             15503 non-null  float64
 8   max_power          15503 non-null  float64
 9   seats              15503 non-null  float64
 10  selling_price      15503 non-null  float64
dtypes: float64(5), int64(2), object(4)
memory usage: 1.4+ MB

In [84]:
df.duplicated().sum()

np.int64(302)

In [85]:
df = df.drop_duplicates()
df.duplicated().sum()

np.int64(0)

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15201 entries, 0 to 15660
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              15201 non-null  object
 1   vehicle_age        15201 non-null  int64
 2   km_driven          15201 non-null  int64
 3   seller_type        15201 non-null  object
 4   fuel_type          15201 non-null  object
 5   transmission_type  15201 non-null  object
 6   mileage            15201 non-null  float64
 7   engine             15201 non-null  float64
 8   max_power          15201 non-null  float64
 9   seats              15201 non-null  float64
 10  selling_price      15201 non-null  float64
dtypes: float64(5), int64(2), object(4)
memory usage: 1.4+ MB

In [87]:
df.describe()

,vehicle_age,km_driven,mileage,engine,max_power,seats,selling_price
count,15201.000000,1.520100e+04,15201.000000,15201.000000,15201.00000,15201.000000,1.520100e+04
mean,6.038682,5.561668e+04,19.690599,1453.042168,99.96576,5.315242,1.038727e+06
std,3.016198,5.185375e+04,4.001321,486.336167,41.89700,0.797338,1.623231e+07
min,0.000000,1.000000e+02,4.000000,793.000000,38.40000,0.000000,5.000000e+02
25%,4.000000,3.000000e+04,17.090000,1197.000000,74.00000,5.000000,3.850000e+05
50%,6.000000,5.000000e+04,19.670000,1248.000000,88.50000,5.000000,5.550000e+05
75%,8.000000,7.000000e+04,22.320000,1498.000000,113.42000,5.000000,8.250000e+05
max,29.000000,3.800000e+06,33.540000,6592.000000,626.00000,9.000000,1.000000e+09

In [88]:
be = len(df)
df = df[df['selling_price'] != 999999999]

df = df[df['selling_price']>=10000]

df=df[df['seats']>0]

af = len(df)
print(f" removed :{be - af} rows with impossible values")
print(f"remaining rows{af}")

 removed :10 rows with impossible values
remaining rows15191

In [89]:
df.describe()

,vehicle_age,km_driven,mileage,engine,max_power,seats,selling_price
count,15191.000000,1.519100e+04,15191.000000,15191.000000,15191.000000,15191.000000,1.519100e+04
mean,6.037786,5.562413e+04,19.691486,1453.094135,99.965519,5.315845,7.760133e+05
std,3.014212,5.186715e+04,4.001262,486.477026,41.909578,0.795005,8.986222e+05
min,0.000000,1.000000e+02,4.000000,793.000000,38.400000,2.000000,4.000000e+04
25%,4.000000,3.000000e+04,17.100000,1197.000000,74.000000,5.000000,3.850000e+05
50%,6.000000,5.000000e+04,19.670000,1248.000000,88.500000,5.000000,5.550000e+05
75%,8.000000,7.000000e+04,22.320000,1498.000000,113.420000,5.000000,8.250000e+05
max,29.000000,3.800000e+06,33.540000,6592.000000,626.000000,9.000000,3.950000e+07

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 15191 entries, 0 to 15660
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   brand              15191 non-null  object
 1   vehicle_age        15191 non-null  int64
 2   km_driven          15191 non-null  int64
 3   seller_type        15191 non-null  object
 4   fuel_type          15191 non-null  object
 5   transmission_type  15191 non-null  object
 6   mileage            15191 non-null  float64
 7   engine             15191 non-null  float64
 8   max_power          15191 non-null  float64
 9   seats              15191 non-null  float64
 10  selling_price      15191 non-null  float64
dtypes: float64(5), int64(2), object(4)
memory usage: 1.4+ MB

In [91]:
df = pd.get_dummies(df,columns=['brand','seller_type','fuel_type','transmission_type'],drop_first = True)
print(f"shape after encoding :{df.shape}")
print(f"sample of new columns :{[c for c in df.columns if '_' in c][:10]}")

shape after encoding :(15191, 45)
sample of new columns :['vehicle_age', 'km_driven', 'max_power', 'selling_price', 'brand_BMW', 'brand_Bentley', 'brand_Datsun', 'brand_Ferrari', 'brand_Force', 'brand_Ford']

In [92]:
df

,vehicle_age,km_driven,mileage,engine,max_power,seats,selling_price,brand_BMW,brand_Bentley,brand_Datsun,...,brand_Toyota,brand_Volkswagen,brand_Volvo,seller_type_Individual,seller_type_Trustmark Dealer,fuel_type_Diesel,fuel_type_Electric,fuel_type_Lpg,fuel_type_Petrol,transmission_type_Manual
0,7,67647,19.87,1461.0,83.80,5.0,575000.0,False,False,False,...,False,False,False,False,False,True,False,False,False,True
1,3,52000,33.54,998.0,67.04,5.0,435000.0,False,False,False,...,False,False,False,False,False,False,False,False,False,True
2,3,48959,19.67,1497.0,117.60,5.0,875000.0,False,False,False,...,False,False,False,False,False,False,False,False,True,True
3,6,82000,15.40,2179.0,88.50,8.0,925000.0,False,False,False,...,False,False,False,False,False,True,False,False,False,True
4,4,34000,16.00,2179.0,140.00,7.0,1175000.0,False,False,False,...,False,False,False,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15656,7,127731,20.77,1248.0,88.80,7.0,665000.0,False,False,False,...,False,False,False,False,False,True,False,False,False,True
15657,11,59000,16.09,1248.0,103.20,5.0,249000.0,False,False,False,...,False,True,False,False,False,False,False,False,True,True
15658,7,20000,20.51,998.0,67.04,5.0,250000.0,False,False,False,...,False,False,False,True,False,False,False,False,True,True
15659,2,15000,18.60,1197.0,81.86,5.0,620000.0,False,False,False,...,False,False,False,False,False,False,False,False,True,True
15660,2,30000,20.28,1462.0,103.25,5.0,960000.0,False,False,False,...,False,False,False,True,False,False,False,False,True,False

In [93]:
x = df.drop(columns =['selling_price'])
y = df['selling_price']
print(f"features :{x.shape[0]} rows x{x.shape[1]} columns")
print(f"target selling price - {y.min():,} to {y.max():,}")
print(f" target mean : {y.mean():,.0f}, median :{y.median():,.0f}")

features :15191 rows x44 columns
target selling price - 40,000.0 to 39,500,000.0
 target mean : 776,013, median :555,000

Task 3 : Base line of MAE

In [94]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split,cross_val_score,KFold
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
import warnings

print("all  imports ready")

all  imports ready

In [95]:
x_train,x_test,y_train,y_test = train_test_split(
    x,y,test_size =0.2,random_state = 42
)

print(f" train: {x_train.shape[0]} rows ({x_train.shape[0]/len(x)*100:.0f}%)")
print(f" test : {x_test.shape[0]} rows ({x_test.shape[0]/len(x)*100:.0f})")

 train: 12152 rows (80%)
 test : 3039 rows (20)

In [96]:
numeric_cols =["vehicle_age","km_driven","mileage","engine","max_power","seats"]

scaler = StandardScaler()
x_train[numeric_cols] = scaler.fit_transform(x_train[numeric_cols])

In [97]:
x_train

,vehicle_age,km_driven,mileage,engine,max_power,seats,brand_BMW,brand_Bentley,brand_Datsun,brand_Ferrari,...,brand_Toyota,brand_Volkswagen,brand_Volvo,seller_type_Individual,seller_type_Trustmark Dealer,fuel_type_Diesel,fuel_type_Electric,fuel_type_Lpg,fuel_type_Petrol,transmission_type_Manual
5420,-0.675379,-0.749895,-0.003397,0.280854,0.506303,-0.397352,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
11367,-0.343721,1.602734,0.775315,0.089440,-0.037335,-0.397352,False,False,False,False,...,False,False,False,True,False,True,False,False,False,True
5190,0.651252,-0.334725,0.662276,0.262330,0.626473,-0.397352,False,False,False,False,...,False,False,False,False,False,True,False,False,False,True
8242,-1.338694,-1.057789,-0.651485,3.166469,3.860053,-1.659408,True,False,False,False,...,False,False,False,False,False,True,False,False,False,False
12335,0.319594,-0.265530,1.586682,0.089440,-0.037096,-0.397352,False,False,False,False,...,False,False,False,False,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5282,-0.675379,0.795460,0.164905,-0.425114,0.073020,-0.397352,False,False,False,False,...,False,True,False,False,False,True,False,False,False,True
13811,-0.012063,-0.011815,-0.023492,1.112372,-0.278873,-0.397352,True,False,False,False,...,False,False,False,False,False,True,False,False,False,False
5483,2.309541,-0.357790,0.004139,-1.355426,-1.289067,-0.397352,False,False,False,False,...,False,False,False,True,False,False,False,False,True,True
871,0.651252,0.334160,1.084287,-0.688565,-0.721730,-0.397352,False,False,False,False,...,False,False,False,False,False,True,False,False,False,True
7412,-0.343721,1.026109,-0.010933,0.013286,0.198696,-0.397352,False,False,False,False,...,False,False,False,True,False,True,False,False,False,True

In [98]:
x_test[numeric_cols] =scaler.fit_transform(x_test[numeric_cols])

In [99]:
x_test

,vehicle_age,km_driven,mileage,engine,max_power,seats,brand_BMW,brand_Bentley,brand_Datsun,brand_Ferrari,...,brand_Toyota,brand_Volkswagen,brand_Volvo,seller_type_Individual,seller_type_Trustmark Dealer,fuel_type_Diesel,fuel_type_Electric,fuel_type_Lpg,fuel_type_Petrol,transmission_type_Manual
13485,0.982272,0.051015,-1.650033,2.141290,0.018165,3.327897,False,False,False,False,...,True,False,False,False,False,True,False,False,False,True
4118,0.650038,0.180876,-1.132968,1.496882,-0.252856,2.086218,False,False,False,False,...,False,False,False,True,False,True,False,False,False,True
11579,0.650038,-0.078845,0.156019,-0.512033,-0.479100,-0.397141,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
2854,-1.011133,-0.273635,-0.495826,0.293988,0.520144,-0.397141,False,False,False,False,...,False,False,False,True,False,False,False,False,True,True
5665,1.314506,-0.017966,-0.887913,-0.512033,-0.335341,-0.397141,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10185,0.982272,0.076987,-0.890364,-0.407700,0.093580,-0.397141,False,False,False,False,...,False,True,False,False,False,False,False,False,True,True
1526,-0.346665,-0.449660,1.334731,-1.326237,-1.082417,-0.397141,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
9663,-1.011133,-0.208705,-0.824199,1.496882,0.960848,2.086218,False,False,False,False,...,False,False,False,True,False,True,False,False,False,True
10454,-1.343368,-0.663215,-0.275277,-0.512033,-0.409341,-0.397141,False,False,False,False,...,False,False,False,True,False,False,False,False,True,True
11584,-1.011133,-0.702173,0.192777,-0.919135,-0.758134,-0.397141,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True

In [102]:
model = LinearRegression()
model.fit(x_train,y_train)

print(f"model trained")
print(f"number of coeffients :{len(model.coef_)}")
print(f"intercept : {model.intercept_:,.0f}")

model trained
number of coeffients :44
intercept : 1,350,569

In [103]:
model.coef_

array([-2.33110639e+05, -4.65354013e+04, -1.75034906e+04,  1.70378521e+05,
        2.66015477e+05,  2.24560460e+04,  5.20925002e+05,  6.31514309e+06,
       -7.47635651e+05,  3.37384686e+07, -7.63684511e-08, -6.59032180e+05,
       -6.70582568e+05, -6.12467653e+05, -7.59662385e+05, -7.60225648e+05,
        3.39784822e+05, -3.30497816e+05, -2.09152089e+05,  1.57730693e+06,
        2.60743268e+06, -3.29673043e+05, -8.40013663e+05, -5.46955554e+05,
        2.85160590e+06,  1.25728548e-08,  2.23702193e+05,  2.89669167e+05,
       -7.11616907e+05,  2.18641239e+06, -6.72688959e+05, -6.98491931e-09,
       -7.07857253e+05, -8.63576332e+05, -5.12478719e+05, -6.53121711e+05,
        1.67433753e+06, -1.40275757e+04, -8.48337031e+04,  5.06455564e+04,
        5.01220551e+05,  2.48901149e+05, -1.94703209e+04, -5.74098286e+04])

In [105]:
y_train_predict = model.predict(x_train)
y_train_predict

array([1084638.20761583,  659099.603968  ,  785931.85680934, ...,
       -391865.25793775,  226763.46755741,  735851.34065837])

In [106]:
print(y_train)

5420     1050000.0
11367     725000.0
5190      430000.0
8242     6475000.0
12335     535000.0
           ...
5282      725000.0
13811    2550000.0
5483      140000.0
871       290000.0
7412      600000.0
Name: selling_price, Length: 12152, dtype: float64

In [107]:
train_mae = mean_absolute_error(y_train,y_train_predict)
print(train_mae)

209285.36525265806

In [108]:
y_test_predict = model.predict(x_test)
print(y_test_predict)

[1073249.07945586  584268.08767516  287023.43262138 ... 1307093.46736055
  790979.78764848  624546.83708008]

In [109]:
test_mae = mean_absolute_error(y_test,y_test_predict)
print(test_mae)

207971.20031393907

In [110]:
df["selling_price"].mean()

np.float64(776013.289118557)

In [111]:
df["base_predict"] = 776013.289118557

In [112]:
base_mae = mean_absolute_error(df["selling_price"],df["base_predict"])
print(base_mae)

454679.3425709863